apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sj982fjfu-go
  janus-idp.io/tekton: sj982fjfu-go
  backstage.io/kubernetes-id: sj982fjfu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sj982fjfu-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
