apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sj982fjfu-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sj982fjfu-go 
  name: sj982fjfu-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sj982fjfu-go 
